apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
spec:
  type: NodePort
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 31440
  selector:
    app: keycloak
